server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    
spring:
  jpa:
    show-sql: true
  datasource:    
    url: jdbc:mysql://localhost:3306/user_management
    username: root
    password: 888888      
           